# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: bionic # Ubuntu 18.04

script:
  - python Scripts/set-version.py
  - docker build -t "devedse/devehangmanbot:latest" -f DeveHangmanBot.WebApp/Dockerfile .;
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      echo $TRAVIS_BUILD_NUMBER;
      docker images;
      docker image tag devedse/devehangmanbot:latest "devedse/devehangmanbot:$TRAVIS_BUILD_NUMBER";
      docker push devedse/devehangmanbot;
      docker images;
    fi

notifications:
  email: false