# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: bionic # Ubuntu 14.04

script:
  - python Scripts/set-version.py
  - docker build -t devedse/devehangmanbot:$TRAVIS_BUILD_NUMBER -f DeveHangmanBot.WebApp/Dockerfile .;
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker image tag devedse/devehangmanbot:$TRAVIS_BUILD_NUMBER devedse/devehangmanbot:latest
      docker push devedse/devehangmanbot:$TRAVIS_BUILD_NUMBER;
      docker push devedse/devehangmanbot:latest;
    fi

notifications:
  email: false